// ── Document Category ────────────────────────────────────────────────────────

export type DocumentCategory =
  | 'Documents'
  | 'Notes'
  | 'Code'
  | 'Images'
  | 'Assignments';

export const DOCUMENT_CATEGORIES: DocumentCategory[] = [
  'Documents',
  'Notes',
  'Code',
  'Images',
  'Assignments',
];

// ── Document (matches Supabase table schema) ─────────────────────────────────

export interface Document {
  id: string;
  user_id: string;
  filename: string;
  file_type: string;   // e.g. "PDF", "Java", "PNG", "DOCX", "PPTX"
  mime_type: string;   // e.g. "application/pdf"
  file_size: number;   // bytes
  category: DocumentCategory;
  storage_path: string; // path inside the Supabase bucket
  uploaded_at: string;  // ISO 8601
}

// ── Insert shape (no id / uploaded_at — generated by Supabase) ───────────────

export interface DocumentInsert {
  user_id: string;
  filename: string;
  file_type: string;
  mime_type: string;
  file_size: number;
  category: DocumentCategory;
  storage_path: string;
}

// ── Upload state ─────────────────────────────────────────────────────────────

export type UploadStatus =
  | 'idle'
  | 'uploading'
  | 'saving'
  | 'success'
  | 'error';

// ── Extraction Status & Content (Phase 5A) ───────────────────────────────────

export type ExtractionStatus =
  | 'pending'
  | 'processing'
  | 'completed'
  | 'failed'
  | 'unsupported';

export interface DocumentContent {
  id: string;
  document_id: string;
  user_id: string;
  extracted_text: string | null;
  extraction_status: ExtractionStatus;
  extraction_error: string | null;
  extracted_at: string | null;
  character_count: number;
  word_count: number;
  created_at?: string;
  updated_at?: string;
}

export interface DocumentWithContent extends Document {
  content?: DocumentContent | null;
}

// ── Document Chunks & Embeddings (Phase 5B & 5C) ─────────────────────────────

export type EmbeddingStatus =
  | 'pending'
  | 'processing'
  | 'completed'
  | 'failed';

export interface DocumentChunk {
  id: string;
  document_id: string;
  document_content_id: string;
  user_id: string;
  chunk_index: number;
  content: string;
  character_count: number;
  word_count: number;
  page_number: number | null;
  slide_number: number | null;
  embedding?: number[] | string | null;
  embedding_model?: string | null;
  embedding_status?: EmbeddingStatus;
  embedding_error?: string | null;
  embedded_at?: string | null;
  created_at: string;
}

export interface DocumentChunkInsert {
  document_id: string;
  document_content_id: string;
  user_id: string;
  chunk_index: number;
  content: string;
  character_count: number;
  word_count: number;
  page_number?: number | null;
  slide_number?: number | null;
  embedding?: number[] | string | null;
  embedding_model?: string | null;
  embedding_status?: EmbeddingStatus;
  embedding_error?: string | null;
  embedded_at?: string | null;
}
